### ISSUE TITLE
Failed to run the demo program on Pi3b+

### ISSUE THREAD

**Issue by wqliceman** [erikest/libgrpc_csharp_ext#1]
Hello，erikest！
Failed to run the demo program on Pi3b+
Thank you, because the project needs to use grpc on ARM32, I have encountered a problem. I found your article through Google, tried to run the demo, and encountered the following problems

### error logs:
`
╰─[:)] % ./grpcPiTest.Client
Unhandled exception. System.IO.IOException: Error loading native library "/home/pi/grpcPiTest_Client/libgrpc_csharp_ext.x86.so".
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials)
   at grpcPiTest.Program.Main(String[] args) in C:\Users\SUNKUN\source\repos\grpcPiTest\src\grpcPiTest.Client\Program.cs:line 24
   at grpcPiTest.Program.<Main>(String[] args)
[1]    17410 abort      ./grpcPiTest.Client
`

**Comment by sherlock1982** [comment]
Pi3B+ is ARM8 which is ARM64. 
I bet you published your app with linux-arm64 RID and this package only allows linux-arm RID.
So your file is still original.

I think package maintainer can also allow linux-arm64 RID cause they're generally compatible.
